apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms-deployment
  namespace: order-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-ms
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
        - name: order-ms
          image: quanghongphuoc/order-ms:latest
          ports:
            - containerPort: 8088  # Changed from 8281
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"


---
apiVersion: v1
kind: Service
metadata:
  name: order-ms-svc
  namespace: order-ms
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  selector:
    app: order-ms