apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms-deployment
  namespace: order-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-ms
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
        - name: order-ms
          image: quanghongphuoc/order-ms:latest
          ports:
            - containerPort: 8088  # Changed from 8281
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088  # Changed from 8281
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088  # Changed from 8281
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: order-ms-svc
  namespace: order-ms
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088  # Changed from 8281
  selector:
    app: order-ms