# k8s-manifests/deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: depooptest
  labels:
    name: depooptest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depooptest-deployment  # Changed from DepOopTest-deployment to depooptest-deployment
  namespace: depooptest
  labels:
    app: depooptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depooptest
  template:
    metadata:
      labels:
        app: depooptest
    spec:
      containers:
        - name: depooptest
          image: quanghongphuoc/depooptest:latest
          ports:
            - containerPort: 8088
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"