# k8s-manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: depooptest-service  # Changed from DepOopTest-svc to depooptest-service
  namespace: depooptest
  labels:
    app: depooptest
spec:
  type: LoadBalancer  # Changed from loadBalancer to LoadBalancer (case-sensitive)
  selector:
    app: depooptest  # Must match the label in the deployment
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP